### ISSUE TITLE
Return errors in CodeExecutor class

### ISSUE THREAD

**Issue by roerohan** [csivitu/code-executor#14]
# Return errors in CodeExecutor class

Errors (if any) thrown from the by `this.work()` are not caught/handled in `Worker.ts`.

https://github.com/csivitu/code-executor/blob/b69766f9f629ba31f40afc8198356605041f541d/src/Worker.ts#L50-L58

The goal is to reject the promise in `this.queue.on('global:completed')` in the `CodeExecutor` class if the Worker ran into an error.

https://github.com/csivitu/code-executor/blob/b69766f9f629ba31f40afc8198356605041f541d/src/CodeExecutor.ts#L17-L27

**Comment by alias-rahil** [comment]
I will take this up.

**Comment by roerohan** [comment]
Cool, good luck @alias-rahil

**Comment by roerohan** [comment]
Resolved in #32
